package com.pmo.pmoitserv.Model;
// Generated 27 juil. 2016 12:16:57 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name="action")
public class Action  implements java.io.Serializable {

     @Id
     @Column(name="idAction")
     private int idAction;
     
     @ManyToOne
     @JoinColumn(name="chantier_idChantier")
     private Chantier chantier;
     
     @ManyToOne
     @JoinColumn(name="utilisateur_idUtilisateur")
     private Utilisateur utilisateur;
     
     
     @Column(name="ActionNum")
     private Integer actionNum;
     @Column(name="ActionTitre")
     private String actionTitre;
     @Column(name="ActionStatut")
     private String actionStatut;
     @Column(name="ActionPriorite")
     private Integer actionPriorite;
     @Column(name="ActionRetard")
     private Integer actionRetard;
     @Column(name="ActionCreationDte")
     private Date actionCreationDte;
     @Column(name="ActionCloturePlanDte")
     private Date actionCloturePlanDte;
     @Column(name="ActionClotureRealDte")
     private Date actionClotureRealDte;
     @Column(name="ActionComment")
     private String actionComment;

    public Action() {
    }

	
    public Action(int idAction, Chantier chantier, Utilisateur utilisateur, String actionTitre) {
        this.idAction = idAction;
        this.chantier = chantier;
        this.utilisateur = utilisateur;
        this.actionTitre = actionTitre;
    }
    public Action(int idAction, Chantier chantier, Utilisateur utilisateur, Integer actionNum, String actionTitre, String actionStatut, Integer actionPriorite, Integer actionRetard, Date actionCreationDte, Date actionCloturePlanDte, Date actionClotureRealDte, String actionComment) {
       this.idAction = idAction;
       this.chantier = chantier;
       this.utilisateur = utilisateur;
       this.actionNum = actionNum;
       this.actionTitre = actionTitre;
       this.actionStatut = actionStatut;
       this.actionPriorite = actionPriorite;
       this.actionRetard = actionRetard;
       this.actionCreationDte = actionCreationDte;
       this.actionCloturePlanDte = actionCloturePlanDte;
       this.actionClotureRealDte = actionClotureRealDte;
       this.actionComment = actionComment;
    }
   
    public int getIdAction() {
        return this.idAction;
    }
    
    public void setIdAction(int idAction) {
        this.idAction = idAction;
    }
    public Chantier getChantier() {
        return this.chantier;
    }
    
    public void setChantier(Chantier chantier) {
        this.chantier = chantier;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Integer getActionNum() {
        return this.actionNum;
    }
    
    public void setActionNum(Integer actionNum) {
        this.actionNum = actionNum;
    }
    public String getActionTitre() {
        return this.actionTitre;
    }
    
    public void setActionTitre(String actionTitre) {
        this.actionTitre = actionTitre;
    }
    public String getActionStatut() {
        return this.actionStatut;
    }
    
    public void setActionStatut(String actionStatut) {
        this.actionStatut = actionStatut;
    }
    public Integer getActionPriorite() {
        return this.actionPriorite;
    }
    
    public void setActionPriorite(Integer actionPriorite) {
        this.actionPriorite = actionPriorite;
    }
    public Integer getActionRetard() {
        return this.actionRetard;
    }
    
    public void setActionRetard(Integer actionRetard) {
        this.actionRetard = actionRetard;
    }
    public Date getActionCreationDte() {
        return this.actionCreationDte;
    }
    
    public void setActionCreationDte(Date actionCreationDte) {
        this.actionCreationDte = actionCreationDte;
    }
    public Date getActionCloturePlanDte() {
        return this.actionCloturePlanDte;
    }
    
    public void setActionCloturePlanDte(Date actionCloturePlanDte) {
        this.actionCloturePlanDte = actionCloturePlanDte;
    }
    public Date getActionClotureRealDte() {
        return this.actionClotureRealDte;
    }
    
    public void setActionClotureRealDte(Date actionClotureRealDte) {
        this.actionClotureRealDte = actionClotureRealDte;
    }
    public String getActionComment() {
        return this.actionComment;
    }
    
    public void setActionComment(String actionComment) {
        this.actionComment = actionComment;
    }




}


