package com.pmo.pmoitserv.Model;
// Generated 27 juil. 2016 12:16:57 by Hibernate Tools 4.3.1

import javax.persistence.*;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin")
public class Admin  extends Utilisateur implements java.io.Serializable {


     
   /*  @Column(name="idAdmin")
     private int idAdmin; */
     
 /*    @ManyToOne
     @JoinColumn(name="utilisateur_idUtilisateur")
     private Utilisateur utilisateur; */

    public Admin() {
    }

 /*   public Admin(Utilisateur utilisateur) {
       this.utilisateur = utilisateur;
    } */
   
 /*   public int getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(int idAdmin) {
        this.idAdmin = idAdmin;
    } */
 /*   public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }*/




}


