package com.pmo.pmoitserv.Model;
// Generated 27 juil. 2016 12:16:57 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Consultant generated by hbm2java
 */
@Entity
@Table(name="consultant")
@PrimaryKeyJoinColumn(name="idUtilisateur")
public class Consultant extends Utilisateur implements java.io.Serializable {


 /*    @Id
     @Column(name="idConsultant")
     private int idConsultant;
     
     @ManyToOne
     @JoinColumn(name="utilisateur_idUtilisateur")
     private Utilisateur utilisateur;
*/
    public Consultant() {
    }
/*
    public Consultant(Utilisateur utilisateur) {
       this.utilisateur = utilisateur;
    }
   
    public int getIdConsultant() {
        return this.idConsultant;
    }
    
    public void setIdConsultant(int idConsultant) {
        this.idConsultant = idConsultant;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
*/



}


