package com.pmo.pmoitserv.Model;
// Generated 27 juil. 2016 12:16:57 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Demande generated by hbm2java
 */
@Entity
@Table( name ="demande" )
public class Demande  implements java.io.Serializable {


     @Id
     @Column(name="idDemande")
     private int idDemande;
     
     @ManyToOne
     @JoinColumn(name="projet_idProjet")
     private Projet projet;
     
     @ManyToOne
     @JoinColumn(name="utilisateur_idUtilisateur")
     private Utilisateur utilisateur;
     
     private Integer demandeNum;
     private String demandeLabel;
     private String demandeStatut;
     
     private String demandePriorite;
     private Date demandeDte;
     private Date demandeDecisPlan;
     private Date demandeDecisReal;
     private String demandeComment;

    public Demande() {
    }

	
    public Demande(int idDemande, Projet projet, Utilisateur utilisateur, String demandeLabel) {
        this.idDemande = idDemande;
        this.projet = projet;
        this.utilisateur = utilisateur;
        this.demandeLabel = demandeLabel;
    }
    public Demande(int idDemande, Projet projet, Utilisateur utilisateur, Integer demandeNum, String demandeLabel, String demandeStatut, String demandePriorite, Date demandeDte, Date demandeDecisPlan, Date demandeDecisReal, String demandeComment) {
       this.idDemande = idDemande;
       this.projet = projet;
       this.utilisateur = utilisateur;
       this.demandeNum = demandeNum;
       this.demandeLabel = demandeLabel;
       this.demandeStatut = demandeStatut;
       
       this.demandePriorite = demandePriorite;
       this.demandeDte = demandeDte;
       this.demandeDecisPlan = demandeDecisPlan;
       this.demandeDecisReal = demandeDecisReal;
       this.demandeComment = demandeComment;
    }
   
    public int getIdDemande() {
        return this.idDemande;
    }
    
    public void setIdDemande(int idDemande) {
        this.idDemande = idDemande;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Integer getDemandeNum() {
        return this.demandeNum;
    }
    
    public void setDemandeNum(Integer demandeNum) {
        this.demandeNum = demandeNum;
    }
    public String getDemandeLabel() {
        return this.demandeLabel;
    }
    
    public void setDemandeLabel(String demandeLabel) {
        this.demandeLabel = demandeLabel;
    }
    public String getDemandeStatut() {
        return this.demandeStatut;
    }
    
    public void setDemandeStatut(String demandeStatut) {
        this.demandeStatut = demandeStatut;
    }
   
    public String getDemandePriorite() {
        return this.demandePriorite;
    }
    
    public void setDemandePriorite(String demandePriorite) {
        this.demandePriorite = demandePriorite;
    }
    public Date getDemandeDte() {
        return this.demandeDte;
    }
    
    public void setDemandeDte(Date demandeDte) {
        this.demandeDte = demandeDte;
    }
    public Date getDemandeDecisPlan() {
        return this.demandeDecisPlan;
    }
    
    public void setDemandeDecisPlan(Date demandeDecisPlan) {
        this.demandeDecisPlan = demandeDecisPlan;
    }
    public Date getDemandeDecisReal() {
        return this.demandeDecisReal;
    }
    
    public void setDemandeDecisReal(Date demandeDecisReal) {
        this.demandeDecisReal = demandeDecisReal;
    }
    public String getDemandeComment() {
        return this.demandeComment;
    }
    
    public void setDemandeComment(String demandeComment) {
        this.demandeComment = demandeComment;
    }




}


