package com.pmo.pmoitserv.Model;
// Generated 27 juil. 2016 12:16:57 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Intervenant generated by hbm2java
 */
@Entity
@Table(name="intervenant")
@PrimaryKeyJoinColumn(name="idUtilisateur")
public class Intervenant extends Utilisateur implements java.io.Serializable {


/*     @Id
     @Column(name="idIntervenant")
     private int idIntervenant;
     
     @ManyToOne
     @JoinColumn(name="utilisateur_idUtilisateur")
     private Utilisateur utilisateur;
*/
    public Intervenant() {
    }
/*
    public Intervenant(Utilisateur utilisateur) {
       this.utilisateur = utilisateur;
    }
   
    public int getIdIntervenant() {
        return this.idIntervenant;
    }
    
    public void setIdIntervenant(int idIntervenant) {
        this.idIntervenant = idIntervenant;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

*/


}


