package com.pmo.pmoitserv.Model;
// Generated 27 juil. 2016 12:16:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Partenaire generated by hbm2java
 */
@Entity
@Table(name="partenaire")
public class Partenaire  implements java.io.Serializable {


     @Id
     @Column(name="idPartenaire")
     private int idPartenaire;
     @Column(name="PartenaireNom")
     private String partenaireNom;
     
     @ManyToMany(cascade = {CascadeType.ALL})
     @JoinTable(name="partenaire_compte", 
		joinColumns={@JoinColumn(name="partenaire_idPartenaire")}, 
		inverseJoinColumns={@JoinColumn(name="compte_idCompte")})
     private Set<Compte> comptes = new HashSet<Compte>(0);

    public Partenaire() {
    }

	
    public Partenaire(int idPartenaire) {
        this.idPartenaire = idPartenaire;
    }
    public Partenaire(int idPartenaire, String partenaireNom, Set<Compte> comptes) {
       this.idPartenaire = idPartenaire;
       this.partenaireNom = partenaireNom;
       this.comptes = comptes;
    }
   
    public int getIdPartenaire() {
        return this.idPartenaire;
    }
    
    public void setIdPartenaire(int idPartenaire) {
        this.idPartenaire = idPartenaire;
    }
    public String getPartenaireNom() {
        return this.partenaireNom;
    }
    
    public void setPartenaireNom(String partenaireNom) {
        this.partenaireNom = partenaireNom;
    }
    public Set<Compte> getComptes() {
        return this.comptes;
    }
    
    public void setComptes(Set<Compte> comptes) {
        this.comptes = comptes;
    }




}


