package com.pmo.pmoitserv.Model;
// Generated 27 juil. 2016 12:16:57 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Risque generated by hbm2java
 */
@Entity
@Table(name="risque")
public class Risque  implements java.io.Serializable {

     @Id
     @Column(name="idRisque")
     private int idRisque;
     
     @ManyToOne
     @JoinColumn(name="projet_idProjet")
     private Projet projet;
     
     @Column(name="RisqueNum")
     private Integer risqueNum;
     @Column(name="RisqueDescrip")
     private String risqueDescrip;
     @Column(name="RisqueProbabilite")
     private Integer risqueProbabilite;
     @Column(name="RisqueImpacte")
     private Integer risqueImpacte;
     @Column(name="RisqueKRI")
     private Integer risqueKri;
     @Column(name="RisqueDisposition")
     private String risqueDisposition;
     @Column(name="RisquePlanAction")
     private String risquePlanAction;
     @Column(name="RisqueStatut")
     private String risqueStatut;
     @Column(name="RisqueDecision")
     private String risqueDecision;
     @Column(name="RisqueDetectionDte")
     private Date risqueDetectionDte;
     @Column(name="RisqueQualifDte")
     private Date risqueQualifDte;
     @Column(name="RisqueClotureDte")
     private Date risqueClotureDte;
     @Column(name="RisqueComment")
     private String risqueComment;
    public Risque() {
    }

	
    public Risque(int idRisque, Projet projet, String risqueDescrip) {
        this.idRisque = idRisque;
        this.projet = projet;
        this.risqueDescrip = risqueDescrip;
    }
    public Risque(int idRisque, Projet projet, Integer risqueNum, String risqueDescrip, Integer risqueProbabilite, Integer risqueImpacte, Integer risqueKri, String risqueDisposition, String risquePlanAction, String risqueStatut, String risqueDecision, Date risqueDetectionDte, Date risqueQualifDte, Date risqueClotureDte, String risqueComment) {
       this.idRisque = idRisque;
       this.projet = projet;
       this.risqueNum = risqueNum;
       this.risqueDescrip = risqueDescrip;
       this.risqueProbabilite = risqueProbabilite;
       this.risqueImpacte = risqueImpacte;
       this.risqueKri = risqueKri;
       this.risqueDisposition = risqueDisposition;
       this.risquePlanAction = risquePlanAction;
       this.risqueStatut = risqueStatut;
       this.risqueDecision = risqueDecision;
       this.risqueDetectionDte = risqueDetectionDte;
       this.risqueQualifDte = risqueQualifDte;
       this.risqueClotureDte = risqueClotureDte;
       this.risqueComment = risqueComment;
    }
   
    public int getIdRisque() {
        return this.idRisque;
    }
    
    public void setIdRisque(int idRisque) {
        this.idRisque = idRisque;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public Integer getRisqueNum() {
        return this.risqueNum;
    }
    
    public void setRisqueNum(Integer risqueNum) {
        this.risqueNum = risqueNum;
    }
    public String getRisqueDescrip() {
        return this.risqueDescrip;
    }
    
    public void setRisqueDescrip(String risqueDescrip) {
        this.risqueDescrip = risqueDescrip;
    }
    public Integer getRisqueProbabilite() {
        return this.risqueProbabilite;
    }
    
    public void setRisqueProbabilite(Integer risqueProbabilite) {
        this.risqueProbabilite = risqueProbabilite;
    }
    public Integer getRisqueImpacte() {
        return this.risqueImpacte;
    }
    
    public void setRisqueImpacte(Integer risqueImpacte) {
        this.risqueImpacte = risqueImpacte;
    }
    public Integer getRisqueKri() {
        return this.risqueKri;
    }
    
    public void setRisqueKri(Integer risqueKri) {
        this.risqueKri = risqueKri;
    }
    public String getRisqueDisposition() {
        return this.risqueDisposition;
    }
    
    public void setRisqueDisposition(String risqueDisposition) {
        this.risqueDisposition = risqueDisposition;
    }
    public String getRisquePlanAction() {
        return this.risquePlanAction;
    }
    
    public void setRisquePlanAction(String risquePlanAction) {
        this.risquePlanAction = risquePlanAction;
    }
    public String getRisqueStatut() {
        return this.risqueStatut;
    }
    
    public void setRisqueStatut(String risqueStatut) {
        this.risqueStatut = risqueStatut;
    }
    public String getRisqueDecision() {
        return this.risqueDecision;
    }
    
    public void setRisqueDecision(String risqueDecision) {
        this.risqueDecision = risqueDecision;
    }
    public Date getRisqueDetectionDte() {
        return this.risqueDetectionDte;
    }
    
    public void setRisqueDetectionDte(Date risqueDetectionDte) {
        this.risqueDetectionDte = risqueDetectionDte;
    }
    public Date getRisqueQualifDte() {
        return this.risqueQualifDte;
    }
    
    public void setRisqueQualifDte(Date risqueQualifDte) {
        this.risqueQualifDte = risqueQualifDte;
    }
    public Date getRisqueClotureDte() {
        return this.risqueClotureDte;
    }
    
    public void setRisqueClotureDte(Date risqueClotureDte) {
        this.risqueClotureDte = risqueClotureDte;
    }
    public String getRisqueComment() {
        return this.risqueComment;
    }
    
    public void setRisqueComment(String risqueComment) {
        this.risqueComment = risqueComment;
    }




}


