package com.pmo.pmoitserv.Model;
// Generated 27 juil. 2016 12:16:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sousprojet generated by hbm2java
 */
@Entity
@Table(name="sousprojet")
public class Sousprojet  implements java.io.Serializable {

     @Id
     @Column(name="idSousprojet")
     private int idSousprojet;
     
     @ManyToOne
     @JoinColumn(name="projet_idProjet")
     private Projet projet;
     
     @Column(name="SousprojetLabel")
     private String sousprojetLabel;
     
     @OneToMany(mappedBy="sousprojet")
     private Set<Chantier> chantiers = new HashSet<Chantier>(0);

    public Sousprojet() {
    }

	
    public Sousprojet(int idSousprojet, Projet projet) {
        this.idSousprojet = idSousprojet;
        this.projet = projet;
    }
    public Sousprojet(int idSousprojet, Projet projet, String sousprojetLabel, Set<Chantier> chantiers) {
       this.idSousprojet = idSousprojet;
       this.projet = projet;
       this.sousprojetLabel = sousprojetLabel;
       this.chantiers = chantiers;
    }
   
    public int getIdSousprojet() {
        return this.idSousprojet;
    }
    
    public void setIdSousprojet(int idSousprojet) {
        this.idSousprojet = idSousprojet;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public String getSousprojetLabel() {
        return this.sousprojetLabel;
    }
    
    public void setSousprojetLabel(String sousprojetLabel) {
        this.sousprojetLabel = sousprojetLabel;
    }
    public Set<Chantier> getChantiers() {
        return this.chantiers;
    }
    
    public void setChantiers(Set<Chantier> chantiers) {
        this.chantiers = chantiers;
    }




}


